name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-docker:
    if: ${{ !startsWith(github.event.head_commit.message, '[bot]') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2025-22.04
            artifact-name: Athena
            build-options: "-Ponlylinuxathena"
          - container: wpilib/raspbian-cross-ubuntu:bookworm-22.04
            artifact-name: Arm32
            build-options: "-Ponlylinuxarm32"
          - container: wpilib/aarch64-cross-ubuntu:bookworm-22.04
            artifact-name: Arm64
            build-options: "-Ponlylinuxarm64"
          - container: wpilib/ubuntu-base:22.04
            artifact-name: Linux
            build-options: ""
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew build ${{ matrix.build-options }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-host:
    name: "Build - Win64"
    runs-on: windows-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[bot]') }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew build -Pbuildalldesktop
      - uses: actions/upload-artifact@v4
        with:
          name: Win64
          path: build/allOutputs
  combine:
    name: Combine
    runs-on: ubuntu-latest
    needs: [build-docker, build-host]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wpilibsuite/build-tools
      - uses: actions/download-artifact@v4
        with:
          path: combiner/products/build/allOutputs
      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Combine
        run: ./gradlew publish -Pthirdparty -PreleaseRepoPublish
        working-directory: combiner
      - uses: actions/upload-artifact@v4
        with:
          name: Maven
          path: ~/releases/maven/release
  push:
    name: Push to branch
    runs-on: ubuntu-latest
    needs: combine
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: Maven
          path: ~/releases
      - name: Copy releases from main
        continue-on-error: true
        run: |
          rm -rf releases
          git checkout origin/main -- releases
      - name: Combine new release
        run: |
          mkdir -p releases
          cp -r ~/releases/* releases/
      - name: Push to branch
        run: |
          git config --global user.name "Ishan Karmakar"
          git config --global user.email "ishan.karmakar24@gmail.com"
          git add .
          git commit -m "[bot] Update releases"
          git push
